(rocq.theory
 (name Kalman)
 (package kalman)
 (synopsis "Kalman filter properties using Rocq and MathComp")
 (flags :standard -w -notation-overridden -w -ambiguous-paths)
 (modules mxnotation mxdefinite mxloewner spectral expectation mxherm mxhermform
          mxfrob mxtopo mxmonotone riccati_def riccati_cont riccati_mono obsv_bound
          lyapunov gramian_infty detectability spec_rad lyap_inv riccati_unique dare
          kalman duality faddeev seqmx/riccati_seqmx seqmx/experiments)
 (plugins rocq-elpi.elpi)
 (theories elpi_elpi elpi HB mathcomp.boot mathcomp.algebra mathcomp.order
           mathcomp.fingroup mathcomp.finmap mathcomp.field mathcomp.solvable
           mathcomp.classical mathcomp.reals mathcomp.analysis CoqEAL.refinements
           Bignums Stdlib))
(include_subdirs qualified)
