# Follow https://github.com/coq-community/templates to regenerate from meta.yml.
name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:2.5.0-rocq-prover-9.1'
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'unn-rocq-kalman.opam'
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              opam pin remove dune -y
              opam install -y "dune>=3.21"
              opam pin add -n -y -k path unn-rocq-kalman .
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 unn-rocq-kalman --deps-only
            endGroup
